[FEAT] 프로필 페이지
wisestudy/wisestudy-android pull request #11
Opened 2020-05-24 07:40 UTC by jonghyunH

### 관련이슈
- #5 

### 작업내용
- test 

### 특이사항
-

### 작업시간
- 0d 0h 0m

2020-05-24 07:41 UTC, edw216 submitted a review, later dismissed

2020-05-24 07:41 UTC, leewoongi commented on app/src/main/res/layout/information1.xml
> +        android:id="@+id/textView3"
아이디 이름 -> textview3 (x) / 좀 더 정확한 id 이름을 넣어주세요

2020-05-24 07:45 UTC, jonghyunH commented on app/src/main/res/layout/information1.xml
> +        android:id="@+id/textView3"
수정 했습니다

2020-05-26 04:58 UTC, MunSeongKim submitted a review, later dismissed

2020-05-26 05:13 UTC, leewoongi submitted a review, later dismissed

2020-05-27 06:42 UTC, MunSeongKim reviewed
departmentView2
line4
nameRactangle2
interestBtn1, 2, 3
groupBtn2

---

전체 나열이 힘든데 위와 같은 버튼이나 뷰가 사용되는 목적이나 의미가 있지 않을까요??
1,2,3은 굉장히 안좋은 id 네이밍 습관입니다 :)

2020-05-28 12:35 UTC, leewoongi submitted a review, later dismissed

2020-05-29 02:20 UTC, leewoongi reviewed
xml 명 다시 circle, rectangle, .. 전부다 어디에 쓰이는 원인지 알아야지 다음뻔에 원 만들어야 될때 되면 circle1 이렇게 지을수는없자나 네이밍 좀 더 신경써줘

2020-05-29 04:52 UTC, leewoongi reviewed
마지막으로 다시 한번
activity_profile_greycircle  밑에 activiy_profile_menuredrectangle 이렇게 가자 네이밍은 다시 한번 정리해서 올려줄께

[what]_[where]_[description]
액티비티/ 플래그먼트 _ 어떤 액티비티인지 _ 무슨역할하는지 이렇게 전부 통일하자

2020-05-29 07:40 UTC, leewoongi approved these changes
수정하느라 고생했어~

2020-05-30 17:18 UTC, MunSeongKim requested changes
[as-is]
activity_myinformation_greycircle.xml
[to-be]
activity_myinformation_gray_circle.xml

to-be가 좀더 가독성이 좋을 것 같아요~ 단어는 언더바로 구분해주면 좋을 듯 합니다~
전체적으로 보고 수정부탁드려요

2020-05-31 09:15 UTC, MunSeongKim approved these changes

2020-05-31 09:16 UTC, MunSeongKim commented
> [as-is]
> activity_myinformation_greycircle.xml
> [to-be]
> activity_myinformation_gray_circle.xml
> 
> to-be가 좀더 가독성이 좋을 것 같아요~ 단어는 언더바로 구분해주면 좋을 듯 합니다~
> 전체적으로 보고 수정부탁드려요

해당 수정사항은 리팩토링 이슈로 별도 처리합니다

2020-05-31 09:16 UTC, merged