[FEAT] 메인페이지 수정 #20
wisestudy/wisestudy-android pull request #21
Opened 2020-06-19 18:07 UTC by edw216

### 관련이슈
- #20 
### 작업내용
-  메인페이지 주석 제거 및 삭제파일 복구

### 특이사항
- UserCreateActivity에 버튼 클릭이벤트 추가(종현이 코드)

### 작업시간
- 0d 0h 40m

2020-06-19 18:47 UTC, MunSeongKim requested changes

2020-06-19 18:47 UTC, MunSeongKim commented on app/src/main/java/com/wisestudy/planner/activity/PlannerActivity.java
> +    private ArrayList<plannerVO> recyclerDataList;
plannerVO -> PlannerVO

2020-06-19 18:47 UTC, MunSeongKim commented on app/src/main/java/com/wisestudy/planner/activity/PlannerActivity.java
> +    private JoinedGroupVO expandListviewAdapter;
클래스와 변수명이 일치안되는거같은거 같ㅔ요

2020-06-19 18:47 UTC, MunSeongKim commented on app/src/main/java/com/wisestudy/planner/vo/JoinedGroupVO.java
> +public class JoinedGroupVO extends BaseExpandableListAdapter {
VO는 Value Object로 값 만을 가지는 객체입니다.

상속으로 확장하는 용도는 아닐 것 같네요, 그리고 메소드 또한 getter/setter만 있어야 할 것 같아요
Adapter를 확장해서 사용하려면 용도에 맞게 변경되어야 할 것 같네요

2020-06-20 09:14 UTC, edw216 commented on app/src/main/java/com/wisestudy/planner/activity/PlannerActivity.java
> +    private ArrayList<plannerVO> recyclerDataList;
수정완료했습니다

2020-06-20 09:14 UTC, edw216 commented on app/src/main/java/com/wisestudy/planner/activity/PlannerActivity.java
> +    private ArrayList<plannerVO> recyclerDataList;
수정했습니다

2020-06-20 09:19 UTC, edw216 commented on app/src/main/java/com/wisestudy/planner/vo/JoinedGroupVO.java
> +public class JoinedGroupVO extends BaseExpandableListAdapter {
module 그룹으로 이동시키고 수정완료했습니다

2020-06-20 09:19 UTC, edw216 commented on app/src/main/java/com/wisestudy/planner/activity/PlannerActivity.java
> +    private JoinedGroupVO expandListviewAdapter;
수정완료했습니다

2020-07-20 05:09 UTC, jonghyunH submitted a review, later dismissed

2020-07-21 08:51 UTC, MunSeongKim requested changes
1. ArrayList -> List로 변경
2. 클래스 필드 private 적용

2020-07-21 08:51 UTC, MunSeongKim commented on app/src/main/java/com/wisestudy/planner/module/recyclerview/RecyclerViewAdapter.java
> +    private ArrayList<PlannerVO> recyclerDataList = null;
collection은 구현체 보다 인터페이스 자료형으로 받는게 좋습니다.

ArrayList > List

2020-07-21 09:56 UTC, leewoongi submitted a review, later dismissed

2020-07-21 12:49 UTC, edw216 commented on app/src/main/java/com/wisestudy/planner/module/recyclerview/RecyclerViewAdapter.java
> +    private ArrayList<PlannerVO> recyclerDataList = null;
List로 수정완료 했습니다.
public으로 한 설정한 이유는 멤버변수가 아니라 생성자 이므로 public으로 하였습니다(위치 수정완료)

2020-07-21 15:22 UTC, leewoongi submitted a review, later dismissed

2020-07-22 07:31 UTC, jonghyunH submitted a review, later dismissed

2020-07-26 08:32 UTC, merged