feat(#24): non_group_member
wisestudy/wisestudy-android pull request #31
Opened 2020-07-24 05:35 UTC by GyuJin-Cho

### 관련이슈
- {#24}

### 작업내용
- 비 그룹원 액티비티 만들기

### 특이사항
- 뷰 페이저 작업 및 이벤트는 구현이 안되있음

### 작업시간
- 0d 6h 0m

2020-07-26 07:26 UTC, leewoongi reviewed
확인해봐

2020-07-26 07:26 UTC, leewoongi commented on app/src/main/java/com/wisestudy/nongroup/activity/NonGruopActivity.java
> +        ViewPager viewPager = findViewById(R.id.viewPager);
여기 viewpager 초기화하는 작업도 위에 데이터 초기화하는거처럼 빼서 정리해주자. 이게 정답은아닌데 어떤건 빼고 어떤건 안에 그냥 넣고 하니까 통일감있게 수정하자 전체적으로 잘짯어

2020-07-26 07:26 UTC, leewoongi commented on app/src/main/java/com/wisestudy/nongroup/activity/NonGruopActivity.java
> +        int margin = (int) (DP * density);
여기는 무슨작업이야??

2020-07-27 14:56 UTC, GyuJin-Cho commented on app/src/main/java/com/wisestudy/nongroup/activity/NonGruopActivity.java
> +        ViewPager viewPager = findViewById(R.id.viewPager);
수정하였습니다.

2020-07-27 14:56 UTC, GyuJin-Cho commented on app/src/main/java/com/wisestudy/nongroup/activity/NonGruopActivity.java
> +        int margin = (int) (DP * density);
수정하였습니다.

2020-07-29 09:47 UTC, MunSeongKim requested changes

2020-07-29 09:47 UTC, MunSeongKim commented on app/src/main/java/com/wisestudy/planner/module/recyclerview/StudySearchRecyclerViewAdapter.java
> +    public class ViewHolder extends RecyclerView.ViewHolder {
클래스 안에서 내부 클래스를 정의한 이유가 있는지...?

2020-07-29 09:47 UTC, MunSeongKim commented on app/src/main/java/com/wisestudy/planner/viewPager/ViewPagerAdapter.java
> +        return (view == (View)o);
객체의 값을 비교하는 것이면 맞을 듯한데, 메소드명의 의미상 객체의 타입을 비교하는 것으로 생각되서
"==" 연산만으로는 비교가 힘들것으로 생각합니다

2020-07-29 18:24 UTC, leewoongi commented on app/src/main/java/com/wisestudy/nongroup/activity/StudySearchActivity.java
> +        String[] name={"1","2","3","4","5","6","7","8","9","10"};
규진 이 방법 말고 Lis<도메인> list =  new ArrayList<>(); 
로 만들어주고 list.add ( 여기다가 도메인 값 ) 받는걸로 연습해봐 내가 보기에 이거 그냥 복붙한거 같은데 한번 바꿔봐

2020-07-29 18:24 UTC, leewoongi commented on app/src/main/java/com/wisestudy/planner/module/recyclerview/StudySearchRecyclerDecoration.java
> +package com.wisestudy.planner.module.recyclerview;
이 클래스가 어떤 일을 하는지 나한테 내일 슬랙으로 설명 ㄱㄱ

2020-07-29 18:24 UTC, leewoongi commented on app/src/main/java/com/wisestudy/planner/module/recyclerview/StudySearchRecyclerViewAdapter.java
> +
이것도 이렇게 받지말고 아까 위의 방식처럼 리스트 하나만들고 타입은 도메인 타입으로

2020-07-29 18:24 UTC, leewoongi commented on app/src/main/java/com/wisestudy/planner/module/recyclerview/StudySearchRecyclerViewAdapter.java
> +    public class ViewHolder extends RecyclerView.ViewHolder {
이거는 나도 생각해봐야겠다 
StudySearchRecyclerViewAdapter.ViewHolder>로 선언하면 ViewHodler는 리사이클러 뷰 홀더를 확장해서 여기서 좀 더 유연하게  데이터들을 관리하려고하는건데 내부에 클래스 만드는지는 잘 모르겠네여;;

2020-07-29 18:24 UTC, leewoongi commented on app/src/main/res/layout/activity_non_group_member.xml
> +    <TextView
여기에 사용자가 입력받아야된다면 textview가 아니고 edittext로 변경

2020-07-30 11:10 UTC, GyuJin-Cho commented on app/src/main/java/com/wisestudy/planner/module/recyclerview/StudySearchRecyclerViewAdapter.java
> +    public class ViewHolder extends RecyclerView.ViewHolder {
뷰홀더를 외부로 사용할려고 하니깐 RecyclerView.Adapter<StudySearchRecyclerViewAdapter.ViewHolder> 이부분이 오류가 나오네요 ㅠㅠ

2020-07-30 11:11 UTC, GyuJin-Cho commented on app/src/main/java/com/wisestudy/planner/viewPager/ViewPagerAdapter.java
> +        return (view == (View)o);
프래그 먼트 뷰페이저로 다시 수정하였습니다.!

2020-07-30 11:11 UTC, GyuJin-Cho commented on app/src/main/java/com/wisestudy/nongroup/activity/StudySearchActivity.java
> +        String[] name={"1","2","3","4","5","6","7","8","9","10"};
도메인 추가 수정완료했습니다!

2020-07-30 11:12 UTC, GyuJin-Cho commented on app/src/main/java/com/wisestudy/planner/module/recyclerview/StudySearchRecyclerDecoration.java
> +package com.wisestudy.planner.module.recyclerview;
삭제하였습니다!

2020-07-30 11:12 UTC, GyuJin-Cho commented on app/src/main/java/com/wisestudy/planner/module/recyclerview/StudySearchRecyclerViewAdapter.java
> +
도메인 타입으로 수정하였습니다!

2020-07-30 11:52 UTC, GyuJin-Cho commented on app/src/main/java/com/wisestudy/planner/module/recyclerview/StudySearchRecyclerViewAdapter.java
> +    public class ViewHolder extends RecyclerView.ViewHolder {
외부 클래스로 수정하였습니다 !!

2020-07-31 09:34 UTC, leewoongi reviewed
framgent 관련된서 네이밍 전부 바꿔 어디에 들어가는 플래그먼트인지, 그리고 그 플래그먼트안에 들어가는 imageview 이런것도 지금 전부 imageView3 이렇게 되어있는데 한 번 전체적으로 수정해

2020-08-02 05:21 UTC, edw216 submitted a review, later dismissed

2020-08-02 07:00 UTC, leewoongi submitted a review, later dismissed

2020-08-02 07:41 UTC, leewoongi approved these changes

2020-08-02 07:42 UTC, edw216 approved these changes

2020-08-02 07:43 UTC, merged