feat(#27) : 운영진관리UI, 그룹원관리UI, 일정등록하기UI 생성
wisestudy/wisestudy-android pull request #32
Opened 2020-07-26 19:07 UTC by jonghyunH

### 관련이슈
- #27  

### 작업내용
- 운영진관리UI, 그룹원관리UI, 일정등록하기UI 생성

### 특이사항
- 그룹원 관리 - 기존 미완성(구현 방법 고민)

### 작업시간
- 0d 6h 0m

2020-07-27 07:01 UTC, leewoongi reviewed
나머지는괜찮은거가어

2020-07-27 07:01 UTC, leewoongi commented on app/src/main/res/layout/activity_group_signup_management.xml
> +            android:text="신청 현황"
string으로 빼서 관리하자. 아래도 전부

2020-07-29 09:50 UTC, MunSeongKim requested changes
이미지 파일의 확장자는 통일되었으면 합니다 ~
대문자 or 소문자

2020-07-29 09:50 UTC, MunSeongKim commented on app/src/main/res/values/strings.xml
> +=======
필요없는 문자열 같아보이는데 확인해주세요~

2020-07-29 09:50 UTC, MunSeongKim commented on app/src/main/res/values/strings.xml
> +>>>>>>> 0c0f1cc03540afa619cc650a5633551e84515fd4
위와 동일

2020-07-29 18:14 UTC, leewoongi submitted a review, later dismissed

2020-07-30 07:36 UTC, jonghyunH commented on app/src/main/res/values/strings.xml
> +=======
네 수정 했습니다

2020-07-30 07:38 UTC, jonghyunH commented on app/src/main/res/values/strings.xml
> +>>>>>>> 0c0f1cc03540afa619cc650a5633551e84515fd4
이 부분은 activity_groupmanagement에서 사용 됩니다
저번에 만들어 놨던거라 이번 커밋에는 안보이는거 같습니다

2020-07-30 08:16 UTC, leewoongi submitted a review, later dismissed

2020-08-06 08:49 UTC, leewoongi submitted a review, later dismissed

2020-08-06 09:31 UTC, GyuJin-Cho submitted a review, later dismissed

2020-08-07 05:13 UTC, leewoongi reviewed
이제 보이지?

2020-08-07 05:13 UTC, leewoongi commented on app/src/main/res/layout/activity_user_create.xml
>          <View
View는 뭐야 ???

2020-08-07 06:42 UTC, MunSeongKim commented on app/src/main/res/values/strings.xml
> +>>>>>>> 0c0f1cc03540afa619cc650a5633551e84515fd4
지금도 확인되고 있네요

2020-08-10 09:00 UTC, closed without merging